SERVER_URL= 'http://localhost:5000'
USERNAME = 'oServ'
PASSWORD = '12345'
SERVER = '192.168.0.101'
PORT_MYSQL = '3306'
DB = 'db'
SQLALCHEMY_DATABASE_URI = f'mysql+pymysql://{USERNAME}:{PASSWORD}@{SERVER}:{PORT_MYSQL}/{DB}'

SQLALCHEMY_TRACK_MODIFICATIONS = True
SECRET_KEY = 'aplicacao_flask'