"""Add initial tables

Revision ID: 5b56739bd35c
Revises: 
Create Date: 2024-09-24 19:42:10.758511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b56739bd35c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CadCliente',
    sa.Column('idCliente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('doc', sa.String(length=30), nullable=False),
    sa.Column('endereco', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=50), nullable=False),
    sa.Column('cep', sa.String(length=9), nullable=False),
    sa.Column('situacao', sa.Boolean(), nullable=True),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.Column('dtCadastro', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('idCliente')
    )
    op.create_index(op.f('ix_CadCliente_idCliente'), 'CadCliente', ['idCliente'], unique=False)
    op.create_table('CadConfig',
    sa.Column('idConfig', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dtRefSistema', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('idConfig')
    )
    op.create_index(op.f('ix_CadConfig_idConfig'), 'CadConfig', ['idConfig'], unique=False)
    op.create_table('CadEmpresa',
    sa.Column('idEmpresa', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nomeEmpresa', sa.String(length=50), nullable=False),
    sa.Column('dtImplantacao', sa.Date(), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('cidade', sa.String(length=50), nullable=False),
    sa.Column('cnpj', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('idEmpresa')
    )
    op.create_index(op.f('ix_CadEmpresa_idEmpresa'), 'CadEmpresa', ['idEmpresa'], unique=False)
    op.create_table('CadFuncionario',
    sa.Column('idFuncionario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('idEquipe', sa.Integer(), nullable=False),
    sa.Column('situacao', sa.Boolean(), nullable=True),
    sa.Column('dtCadastro', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('idFuncionario', 'idUsuario')
    )
    op.create_table('CadOrdemServico',
    sa.Column('idTipoOS', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('situacao', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('idTipoOS')
    )
    op.create_table('CadRequerimento',
    sa.Column('idTipoRequerimento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('emiteOrcamento', sa.Boolean(), nullable=True),
    sa.Column('emiteOS', sa.Boolean(), nullable=True),
    sa.Column('situacao', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('idTipoRequerimento')
    )
    op.create_table('CadServico',
    sa.Column('idServico', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(length=20), nullable=False),
    sa.Column('situacao', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('idServico')
    )
    op.create_table('CadSetor',
    sa.Column('idSetor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('situacao', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('idSetor')
    )
    op.create_table('CadTipoServico',
    sa.Column('idTipoServico', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('idTipoServico')
    )
    op.create_table('CadUsuario',
    sa.Column('idUsuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Usuario', sa.String(length=25), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('situacao', sa.Boolean(), nullable=True),
    sa.Column('isFuncionario', sa.Boolean(), nullable=True),
    sa.Column('isAdmin', sa.Boolean(), nullable=True),
    sa.Column('apiKey', sa.String(length=100), nullable=True),
    sa.Column('dtCadastro', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('idUsuario')
    )
    op.create_table('CadVeiculo',
    sa.Column('idVeiculo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('placa', sa.String(length=50), nullable=False),
    sa.Column('kmRodados', sa.String(length=50), nullable=False),
    sa.Column('idEquipe', sa.Integer(), nullable=False),
    sa.Column('situacao', sa.Boolean(), nullable=True),
    sa.Column('dtCadastro', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('idVeiculo', 'idEquipe')
    )
    op.create_table('CadEquipe',
    sa.Column('idEquipe', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('idSetor', sa.Integer(), nullable=False),
    sa.Column('situacao', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['idSetor'], ['CadSetor.idSetor'], ),
    sa.PrimaryKeyConstraint('idEquipe')
    )
    op.create_index(op.f('ix_CadEquipe_idEquipe'), 'CadEquipe', ['idEquipe'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_CadEquipe_idEquipe'), table_name='CadEquipe')
    op.drop_table('CadEquipe')
    op.drop_table('CadVeiculo')
    op.drop_table('CadUsuario')
    op.drop_table('CadTipoServico')
    op.drop_table('CadSetor')
    op.drop_table('CadServico')
    op.drop_table('CadRequerimento')
    op.drop_table('CadOrdemServico')
    op.drop_table('CadFuncionario')
    op.drop_index(op.f('ix_CadEmpresa_idEmpresa'), table_name='CadEmpresa')
    op.drop_table('CadEmpresa')
    op.drop_index(op.f('ix_CadConfig_idConfig'), table_name='CadConfig')
    op.drop_table('CadConfig')
    op.drop_index(op.f('ix_CadCliente_idCliente'), table_name='CadCliente')
    op.drop_table('CadCliente')
    # ### end Alembic commands ###
