version: '3.9'

services:
  frontend:
    container_name: Angular
    restart: always
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "4200:80"

  backend:
    container_name: Flask
    restart: always
    build:
      context: ../backend
      dockerfile: ../backend/Dockerfile
    ports:
      - "5000:90"
    # depends_on:
    #   - mysql
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

#   ssh:
#     container_name: SSH
#     build:
#       context: .
#       dockerfile: Dockerfile.ssh
#     ports:
#       - "2222:22"

#   mysql:
#     image: mysql:8.0
#     container_name: MySQL
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: oServ
#       MYSQL_DATABASE: db
#     ports:
#       - "33000:3306"
#     volumes:
#       - db-data:/var/lib/mysql

# volumes:
#   db-data:
