"""empty message

Revision ID: 3aec06c6a8b0
Revises: cf9f6b85180a
Create Date: 2024-03-18 21:59:10.446313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3aec06c6a8b0'
down_revision = 'cf9f6b85180a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.alter_column('dtRefSistema',
               existing_type=mysql.VARCHAR(length=6),
               type_=sa.String(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.alter_column('dtRefSistema',
               existing_type=sa.String(length=7),
               type_=mysql.VARCHAR(length=6),
               existing_nullable=False)

    # ### end Alembic commands ###
