"""empty message

Revision ID: d3da68d80073
Revises: 
Create Date: 2024-02-26 23:08:23.704888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3da68d80073'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('idCliente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('doc', sa.String(length=30), nullable=False),
    sa.Column('endereco', sa.String(length=100), nullable=False),
    sa.Column('bairro', sa.String(length=50), nullable=False),
    sa.Column('cidade', sa.String(length=50), nullable=False),
    sa.Column('cep', sa.String(length=9), nullable=False),
    sa.Column('situacao', sa.Boolean(), nullable=False),
    sa.Column('observacao', sa.String(length=255), nullable=False),
    sa.Column('dtCadastro', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('idCliente')
    )
    op.create_table('controle',
    sa.Column('idControle', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nomeEmpresa', sa.String(length=50), nullable=False),
    sa.Column('dtRefSistema', sa.String(length=6), nullable=False),
    sa.Column('dtImplantacao', sa.String(length=50), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('idControle')
    )
    op.create_table('servico',
    sa.Column('idServico', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(length=20), nullable=False),
    sa.Column('situacao', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('idServico')
    )
    op.create_table('setor',
    sa.Column('idSetor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('idSetor')
    )
    op.create_table('tipo_requerimento',
    sa.Column('idTipoRequerimento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('emiteOrcamento', sa.Boolean(), nullable=False),
    sa.Column('emiteOS', sa.Boolean(), nullable=False),
    sa.Column('situacao', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('idTipoRequerimento')
    )
    op.create_table('usuario',
    sa.Column('idUser', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user', sa.String(length=25), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('situacao', sa.Boolean(), nullable=False),
    sa.Column('isAdmin', sa.Boolean(), nullable=False),
    sa.Column('apiKey', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('idUser')
    )
    op.create_table('equipe',
    sa.Column('idEquipe', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('idSetor', sa.Integer(), nullable=False),
    sa.Column('situacao', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['idSetor'], ['setor.idSetor'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idEquipe')
    )
    op.create_table('pre_orcamento',
    sa.Column('idTipoRequerimento', sa.Integer(), nullable=False),
    sa.Column('idServico', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['idServico'], ['servico.idServico'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idTipoRequerimento'], ['tipo_requerimento.idTipoRequerimento'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idTipoRequerimento', 'idServico')
    )
    op.create_table('requerimento',
    sa.Column('idRequerimento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dtRefRequerimento', sa.String(length=6), nullable=False),
    sa.Column('nomeRequerente', sa.String(length=50), nullable=False),
    sa.Column('endRequerente', sa.String(length=255), nullable=False),
    sa.Column('endServico', sa.String(length=255), nullable=False),
    sa.Column('docRequerente', sa.String(length=20), nullable=False),
    sa.Column('idCliente', sa.Integer(), nullable=False),
    sa.Column('idTipoRequerimento', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.String(length=255), nullable=False),
    sa.Column('situacao', sa.Integer(), nullable=False, comment='0 - Requerido, 1 - Cancelado, 2 - Ordem de serviço emitida, 3 - Ordem de serviço em execução, 4 - Ordem de serviço Concluída'),
    sa.Column('dtRequerimento', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['idCliente'], ['cliente.idCliente'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idTipoRequerimento'], ['tipo_requerimento.idTipoRequerimento'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idRequerimento', 'dtRefRequerimento')
    )
    op.create_table('boleto',
    sa.Column('idBoleto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idRequerimento', sa.Integer(), nullable=False),
    sa.Column('dtRefRequerimento', sa.String(length=6), nullable=False),
    sa.Column('valorTotal', sa.String(length=20), nullable=False),
    sa.Column('dtEmissao', sa.String(length=50), nullable=False),
    sa.Column('dtVencimento', sa.String(length=50), nullable=False),
    sa.Column('dtBaixa', sa.String(length=50), nullable=False),
    sa.Column('idCliente', sa.Integer(), nullable=False),
    sa.Column('situacao', sa.Integer(), nullable=False, comment='0 - Boleto emitido, 1 - Boleto cancelado, 2 - Processo de baixa, 3 - Boleto baixado'),
    sa.ForeignKeyConstraint(['idCliente'], ['cliente.idCliente'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idRequerimento'], ['requerimento.idRequerimento'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idBoleto', 'idRequerimento', 'dtRefRequerimento')
    )
    op.create_table('funcionario',
    sa.Column('idFuncionario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('idEquipe', sa.Integer(), nullable=False),
    sa.Column('situacao', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['idEquipe'], ['equipe.idEquipe'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idUser'], ['usuario.idUser'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idFuncionario', 'idUser')
    )
    op.create_table('veiculo',
    sa.Column('idVeiculo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('placa', sa.String(length=50), nullable=False),
    sa.Column('kmRodados', sa.String(length=50), nullable=False),
    sa.Column('idEquipe', sa.Integer(), nullable=False),
    sa.Column('situacao', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['idEquipe'], ['equipe.idEquipe'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idVeiculo', 'idEquipe')
    )
    op.create_table('boleto_servico',
    sa.Column('idBoleto', sa.Integer(), nullable=False),
    sa.Column('idServico', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(length=20), nullable=False),
    sa.Column('dtVencimento', sa.String(length=50), nullable=False),
    sa.Column('complemento', sa.String(length=255), nullable=False),
    sa.Column('situacao', sa.Integer(), nullable=False, comment='0 - Faturado, 1 - Incluido, 3 - Estornado'),
    sa.ForeignKeyConstraint(['idBoleto'], ['boleto.idBoleto'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idServico'], ['servico.idServico'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idBoleto', 'idServico')
    )
    op.create_table('ordem_servico',
    sa.Column('idOS', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dtRefOS', sa.String(length=6), nullable=False),
    sa.Column('idRequerimento', sa.Integer(), nullable=False),
    sa.Column('dtRefRequerimento', sa.String(length=6), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('dtEmissao', sa.String(length=50), nullable=False),
    sa.Column('dtInicio', sa.String(length=50), nullable=False),
    sa.Column('dtTermino', sa.String(length=50), nullable=False),
    sa.Column('idVeiculo', sa.Integer(), nullable=False),
    sa.Column('situacao', sa.Integer(), nullable=False, comment='0 - Emitida, 1 - Cancelada, 2 - Paga, 3 - Em execução, 4 - Finalizada'),
    sa.Column('observacao', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['idRequerimento'], ['requerimento.idRequerimento'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idVeiculo'], ['veiculo.idVeiculo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idOS', 'dtRefOS', 'idRequerimento', 'dtRefRequerimento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordem_servico')
    op.drop_table('boleto_servico')
    op.drop_table('veiculo')
    op.drop_table('funcionario')
    op.drop_table('boleto')
    op.drop_table('requerimento')
    op.drop_table('pre_orcamento')
    op.drop_table('equipe')
    op.drop_table('usuario')
    op.drop_table('tipo_requerimento')
    op.drop_table('setor')
    op.drop_table('servico')
    op.drop_table('controle')
    op.drop_table('cliente')
    # ### end Alembic commands ###
